name: Autograding

on: [push, pull_request]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - uses: education/autograding@v1
